exports.LogTypes = {
    MOVIE: 'MOVIE',
    TV_SHOW: 'TV_SHOW',
    TV_SEASON: 'TV_SEASON',
    TV_EPISODE: 'TV_EPISODE'
}

exports.ListTypes = {
    WATCHLIST: 'WATCHLIST',
    CUSTOM: 'CUSTOM',
    OSCARS: 'OSCARS',
    FTBBW: 'FTBBW',
    FAVORITE_MOVIES: 'FAVORITE_MOVIES',
    FAVORITE_TV_SHOWS: 'FAVORITE_TV_SHOWS',
    FAVORITE_PEOPLE: 'FAVORITE_PEOPLE'
}

exports.ListItemTypes = {
    MOVIE: 'MOVIE',
    TV_SHOW: 'TV_SHOW',
    TV_SEASON: 'TV_SEASON',
    TV_EPISODE: 'TV_EPISODE',
    CATEGORY: 'CATEGORY',
    PERSON: 'PERSON'
}

exports.CategoryLabels = {
    NONE: 'NONE',
    OSCAR: 'OSCAR'
}